title:
  en: Page
  de: Seite
preset: page
icon: page

status:
  draft: true
  unlisted: true
  listed: true

files:
	sortable: false

fields:
  kicker:
    label:
      en: Kicker
      de: Dachzeile
    type: text
    width: 1/3
  headline:
    label:
      en: Headline
      de: Überschrift
    type: text
    width: 2/3
  lead:
    label:
      en: Lead
      de: Vorspann
    type: textarea
    maxlength: 300
    buttons: false
    size: small
  text:
    label:
      en: Content
      de: Inhalt
    type: blocks

sidebar:
  hero:
    label:
      en: Hero image
      de: Hauptbild
    type: files
    layout: cards
    info: "{{ file.dimensions }}"
    template: cover
    image:
      cover: true
      ratio: 16/9
    max: 1
  files:
    label:
      en: Images
      de: Bilder
    type: files
    query: page.images

# columns:
#   - width: 2/3
#     fields:

#   - width: 1/3
#     sections:
#       meta:
#         type: fields
#         fields:

#       pageFiles:
#         headline:
#           en: Files
#           de: Dateien
#         type: files
#         text: "{{ file.filename }}"
#         info: "{{ file.dimensions }}"
