title:
  en: Website
  de: Website

tabs:
  dashboard:
    label:
      en: Dashboard
      de: Dashboard
    icon: dashboard
    columns:
      - width: 1/3
        sections:
          listed:
            headline:
              en: Pages
              de: Seiten
            type: pages
            status: listed
            text: '{{ page.title }}'
            info: 'Seiten: {{ page.children.count }}'

      - width: 1/3
        sections:
          draft:
            type: pages
            headline:
              en: Drafts
              de: Entwürfe
            status: drafts
          unlisted:
            type: pages
            headline:
              en: Not listed
              de: Nicht gelistet
            layout: list
            status: unlisted
          links:
            label: Links
            type: info
            text: |
              * (link: https://de.wikipedia.org/wiki/Hosting text: Hosting target: _blank rel: noopener)

      - width: 1/3
        sections:
          articles-listed:
            type: pages
            headline:
              en: Blog Articles
              de: Blog-Artikel
            parent: site.find("blog")
            status: published
            sortBy: date desc

          articles-draft:
            type: pages
            headline:
              en: Planned Articles
              de: Geplante Artikel
            parent: site.find("blog")
            status: draft
            sortBy: date desc

  settings:
    label:
      en: Settings
      de: Einstellungen
    icon: cog
    columns:
      - width: 1/4
        fields:
          image:
            label:
              en: Image
              de: Bild
            type: files
            layout: cards
            minwidth: 1200
            minheight: 630
            multiple: false
            image:
              cover: true
              ratio: 16/9
            accept:
              mime: image/*
              type: image
            help:
              en: "Minimum dimensions: 1200 x 630 px"
              de: "Mindestformat: 1200 x 630 px"

      - width: 1/2
        fields:
          description:
            label:
              en: Description
              de: Kurzbeschreibung
            type: textarea
            size: small
            minlength: 50
            maxlength: 160
            buttons: false
          tags:
            label: Tags
            type: tags
          footerText:
            label:
              en: Footer
              de: Footer
            type: textarea
            buttons:
              - headlines
              - bold
              - link
              - email

      - width: 1/4
        fields:
          twitter:
            label: Twitter
            type: text
            before: @
            icon: twitter
          instagram:
            label: Instagram
            type: text
            before: @
            icon: instagram
          facebook:
            label: Facebook
            type: text
            before: @
            icon: facebook
          whatsapp:
            label: WhatsApp
            type: tel
            before: "+49"
            icon: whatsapp

  store:
    label:
      en: Store
      de: Geschäft
    icon: cart
    columns:
      - width: 1/2
        fields:
          address:
            label:
              en: Address
              de: Adresse
            type: writer
            inline: true
            marks:
              - bold
              - link
          phone:
            label:
              en: Phone
              de: Telefon
            type: tel
            before: '+49'
            pattern: '^[0-9-+\s()]*$'
            width: 1/2
          email:
            label:
              en: E-Mail
              de: E-Mail
            type: email
            width: 1/2
          googleMaps:
            label: Google Maps
            type: url
            icon: map

      - width: 1/2
        fields:
          brands:
            label:
              en: Brands
              de: Marken
            type: structure
            sortable: true
            limit: 15
            columns:
              name:
                width: 1/1
            fields:
              name:
                label:
                  en: Name
                  de: Name
                type: text
              description:
                label:
                  en: Description
                  de: Beschreibung
                type: textarea
              logo:
                label:
                  en: Logo
                  de: Logo
                type: files
                accept:
                  mime: image/*
                  type: image
                minwidth: 300
                minheight: 300
                multiple: false

  email:
    label:
      en: Form
      de: Formular
    icon: email
    columns:
      - width: 1/2
        fields:
          recipient:
            label:
              en: Recipient
              de: Empfänger
            type: email
            icon: email
            width: 1/2
          sender:
            label:
              en: Sender
              de: Absender
            type: email
            icon: email
            width: 1/2
          subject:
            label:
              en: Subject Contact
              de: Betreff Kontakt
            type: text
            help:
              en: Use variables like {{email}}
              de: Variablen wie {{email}} sind erlaubt
          messageSentText:
            label:
              en: Message sent text
              de: Nachricht gesendet Text
            type: textarea
            size: medium
